/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as ApiUsersRouteImport } from './routes/api/users'
import { Route as ApiReviewsRouteImport } from './routes/api/reviews'
import { Route as ApiRepositoriesRouteImport } from './routes/api/repositories'
import { Route as ApiPullRequestsRouteImport } from './routes/api/pull-requests'
import { Route as ApiPrFilesRouteImport } from './routes/api/pr-files'
import { Route as ApiPrEventsRouteImport } from './routes/api/pr-events'
import { Route as ApiGithubWebhookRouteImport } from './routes/api/github-webhook'
import { Route as ApiCommentsRouteImport } from './routes/api/comments'
import { Route as ApiAuthRouteImport } from './routes/api/auth'
import { Route as ApiTrpcSplatRouteImport } from './routes/api/trpc/$'
import { Route as AuthenticatedPrPrIdRouteImport } from './routes/_authenticated/pr/$prId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ApiUsersRoute = ApiUsersRouteImport.update({
  id: '/api/users',
  path: '/api/users',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReviewsRoute = ApiReviewsRouteImport.update({
  id: '/api/reviews',
  path: '/api/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRepositoriesRoute = ApiRepositoriesRouteImport.update({
  id: '/api/repositories',
  path: '/api/repositories',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPullRequestsRoute = ApiPullRequestsRouteImport.update({
  id: '/api/pull-requests',
  path: '/api/pull-requests',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPrFilesRoute = ApiPrFilesRouteImport.update({
  id: '/api/pr-files',
  path: '/api/pr-files',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPrEventsRoute = ApiPrEventsRouteImport.update({
  id: '/api/pr-events',
  path: '/api/pr-events',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGithubWebhookRoute = ApiGithubWebhookRouteImport.update({
  id: '/api/github-webhook',
  path: '/api/github-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCommentsRoute = ApiCommentsRouteImport.update({
  id: '/api/comments',
  path: '/api/comments',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthRoute = ApiAuthRouteImport.update({
  id: '/api/auth',
  path: '/api/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTrpcSplatRoute = ApiTrpcSplatRouteImport.update({
  id: '/api/trpc/$',
  path: '/api/trpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPrPrIdRoute = AuthenticatedPrPrIdRouteImport.update({
  id: '/pr/$prId',
  path: '/pr/$prId',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/login': typeof LoginRoute
  '/api/auth': typeof ApiAuthRoute
  '/api/comments': typeof ApiCommentsRoute
  '/api/github-webhook': typeof ApiGithubWebhookRoute
  '/api/pr-events': typeof ApiPrEventsRoute
  '/api/pr-files': typeof ApiPrFilesRoute
  '/api/pull-requests': typeof ApiPullRequestsRoute
  '/api/repositories': typeof ApiRepositoriesRoute
  '/api/reviews': typeof ApiReviewsRoute
  '/api/users': typeof ApiUsersRoute
  '/': typeof AuthenticatedIndexRoute
  '/pr/$prId': typeof AuthenticatedPrPrIdRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/api/auth': typeof ApiAuthRoute
  '/api/comments': typeof ApiCommentsRoute
  '/api/github-webhook': typeof ApiGithubWebhookRoute
  '/api/pr-events': typeof ApiPrEventsRoute
  '/api/pr-files': typeof ApiPrFilesRoute
  '/api/pull-requests': typeof ApiPullRequestsRoute
  '/api/repositories': typeof ApiRepositoriesRoute
  '/api/reviews': typeof ApiReviewsRoute
  '/api/users': typeof ApiUsersRoute
  '/': typeof AuthenticatedIndexRoute
  '/pr/$prId': typeof AuthenticatedPrPrIdRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/api/auth': typeof ApiAuthRoute
  '/api/comments': typeof ApiCommentsRoute
  '/api/github-webhook': typeof ApiGithubWebhookRoute
  '/api/pr-events': typeof ApiPrEventsRoute
  '/api/pr-files': typeof ApiPrFilesRoute
  '/api/pull-requests': typeof ApiPullRequestsRoute
  '/api/repositories': typeof ApiRepositoriesRoute
  '/api/reviews': typeof ApiReviewsRoute
  '/api/users': typeof ApiUsersRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/pr/$prId': typeof AuthenticatedPrPrIdRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/login'
    | '/api/auth'
    | '/api/comments'
    | '/api/github-webhook'
    | '/api/pr-events'
    | '/api/pr-files'
    | '/api/pull-requests'
    | '/api/repositories'
    | '/api/reviews'
    | '/api/users'
    | '/'
    | '/pr/$prId'
    | '/api/trpc/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/api/auth'
    | '/api/comments'
    | '/api/github-webhook'
    | '/api/pr-events'
    | '/api/pr-files'
    | '/api/pull-requests'
    | '/api/repositories'
    | '/api/reviews'
    | '/api/users'
    | '/'
    | '/pr/$prId'
    | '/api/trpc/$'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/api/auth'
    | '/api/comments'
    | '/api/github-webhook'
    | '/api/pr-events'
    | '/api/pr-files'
    | '/api/pull-requests'
    | '/api/repositories'
    | '/api/reviews'
    | '/api/users'
    | '/_authenticated/'
    | '/_authenticated/pr/$prId'
    | '/api/trpc/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiAuthRoute: typeof ApiAuthRoute
  ApiCommentsRoute: typeof ApiCommentsRoute
  ApiGithubWebhookRoute: typeof ApiGithubWebhookRoute
  ApiPrEventsRoute: typeof ApiPrEventsRoute
  ApiPrFilesRoute: typeof ApiPrFilesRoute
  ApiPullRequestsRoute: typeof ApiPullRequestsRoute
  ApiRepositoriesRoute: typeof ApiRepositoriesRoute
  ApiReviewsRoute: typeof ApiReviewsRoute
  ApiUsersRoute: typeof ApiUsersRoute
  ApiTrpcSplatRoute: typeof ApiTrpcSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/users': {
      id: '/api/users'
      path: '/api/users'
      fullPath: '/api/users'
      preLoaderRoute: typeof ApiUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/reviews': {
      id: '/api/reviews'
      path: '/api/reviews'
      fullPath: '/api/reviews'
      preLoaderRoute: typeof ApiReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/repositories': {
      id: '/api/repositories'
      path: '/api/repositories'
      fullPath: '/api/repositories'
      preLoaderRoute: typeof ApiRepositoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/pull-requests': {
      id: '/api/pull-requests'
      path: '/api/pull-requests'
      fullPath: '/api/pull-requests'
      preLoaderRoute: typeof ApiPullRequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/pr-files': {
      id: '/api/pr-files'
      path: '/api/pr-files'
      fullPath: '/api/pr-files'
      preLoaderRoute: typeof ApiPrFilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/pr-events': {
      id: '/api/pr-events'
      path: '/api/pr-events'
      fullPath: '/api/pr-events'
      preLoaderRoute: typeof ApiPrEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/github-webhook': {
      id: '/api/github-webhook'
      path: '/api/github-webhook'
      fullPath: '/api/github-webhook'
      preLoaderRoute: typeof ApiGithubWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/comments': {
      id: '/api/comments'
      path: '/api/comments'
      fullPath: '/api/comments'
      preLoaderRoute: typeof ApiCommentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth': {
      id: '/api/auth'
      path: '/api/auth'
      fullPath: '/api/auth'
      preLoaderRoute: typeof ApiAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/trpc/$': {
      id: '/api/trpc/$'
      path: '/api/trpc/$'
      fullPath: '/api/trpc/$'
      preLoaderRoute: typeof ApiTrpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/pr/$prId': {
      id: '/_authenticated/pr/$prId'
      path: '/pr/$prId'
      fullPath: '/pr/$prId'
      preLoaderRoute: typeof AuthenticatedPrPrIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedPrPrIdRoute: typeof AuthenticatedPrPrIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedPrPrIdRoute: AuthenticatedPrPrIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiAuthRoute: ApiAuthRoute,
  ApiCommentsRoute: ApiCommentsRoute,
  ApiGithubWebhookRoute: ApiGithubWebhookRoute,
  ApiPrEventsRoute: ApiPrEventsRoute,
  ApiPrFilesRoute: ApiPrFilesRoute,
  ApiPullRequestsRoute: ApiPullRequestsRoute,
  ApiRepositoriesRoute: ApiRepositoriesRoute,
  ApiReviewsRoute: ApiReviewsRoute,
  ApiUsersRoute: ApiUsersRoute,
  ApiTrpcSplatRoute: ApiTrpcSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.tsx'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
